### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by MobileMon** [estebanuri/facemaskdetector#2]
I love this project! Great job!

Any idea how to recreate it in Flutter?

I can find examples of how to run the tensor flow model, I'm just having trouble painting the boxes around the faces

**Comment by estebanuri** [comment]
Hi MobileMon,
I did some code in Flutter but not much, so to answer that question I'd have to put my hands on code to find it out.

If your idea is to run on both platforms (Android and iOS) maybe you could develop two native apps, you won't find any problems with the TFLite-related thing if you do the analogous procedure I did, but on the [iOS Google Object Detection example](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/ios/).

Hope it helps!
