### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HugoFerreiraStack** [estebanuri/facemaskdetector#3]
Hello, how are you? I followed the guidelines of the project, but he returns this warning to me:
Warning: <i> <b> root project 'android': Unable to resolve additional project configuration. </b>
Details: org.apache.tools.ant.BuildException: Basedir C: \ Users \ Hugo \ Desktop \ examples-master \ examples-master \ lite \ examples \ object_detection \ android \ tensorflow-lite does not exist </i>

**Comment by estebanuri** [comment]
I had the same issue.
Just do the following:
- delete .idea folder, 
- clean project, and rebuild
-  invalidate caches and restart from file menu.
Will solve the problem.
