### ISSUE TITLE
Camera Size

### ISSUE THREAD

**Issue by Gagandeep1408** [estebanuri/facemaskdetector#9]
May i know how i can change camera size?
I need to increase it size.

**Comment by huzain07** [comment]
> May i know how i can change camera size?
> I need to increase it size.

yeah I need to increase it too, any solution?

**Comment by Gagandeep1408** [comment]
Open DetectorActivity and replace with this. 

 private static final Size DESIRED_PREVIEW_SIZE = new Size(1280 , 720);

**Comment by huzain07** [comment]
> Open DetectorActivity and replace with this.
> 
> private static final Size DESIRED_PREVIEW_SIZE = new Size(1280 , 720);

is it make camera preview full screen?

**Comment by Gagandeep1408** [comment]
yes

**Comment by huzain07** [comment]
> yes

i tried it, but it not make full screen, still left some space. is there any way to make it stretch based on phone screen? and thanks for the solution

**Comment by Gagandeep1408** [comment]
1280 x 720 << best size in my example to use
 1280 x 768
 1280 x 960

uses these size to make full screen

**Comment by huzain07** [comment]
> 1280 x 720 << best size in my example to use
> 1280 x 768
> 1280 x 960
> 
> uses these size to make full screen

ah okay, thanks. I'll try it

**Comment by huzain07** [comment]
> 1280 x 720 << best size in my example to use
> 1280 x 768
> 1280 x 960
> 
> uses these size to make full screen

hey, sorry.. can I ask something. in my device, when I using front camera and go to recent app, then back to my app. the face detector on my camera not working anymore. do u facing same problem? or have any solution for that?
